pipeline {
    agent any

    environment {
        IMAGE_NAME = "yourdockerhub/todo-app"
        TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps { 
                git  'https://github.com/Saurabh3499/project.git'
            }
        }

        stage('Build') {
            steps {
                dir('app') {
                    sh 'sudo podman build -t $IMAGE_NAME:$TAG .'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh 'sudo podman run --rm $IMAGE_NAME:$TAG pytest -q'
            }
        }
    }
}

